### ISSUE TITLE
Compiler: gcc Xcode: xcode9.4 C++ 编译失败

### ISSUE THREAD

**Issue by ZPJ8** [jaredtao/HelloCI#2]
![image](https://user-images.githubusercontent.com/26075380/62995463-4fcfd000-be93-11e9-914f-513b1f8c1927.png)
![image](https://user-images.githubusercontent.com/26075380/62995481-6118dc80-be93-11e9-8fe5-70844270a474.png)

**Comment by ZPJ8** [comment]
这个问题怎么解决  @jaredtao

**Comment by jaredtao** [comment]
XCode 9.4的 qmake安装路径 对不上。得找个XCode9.4的镜像，看看qmake装在哪了，把路径改掉。

**Comment by jaredtao** [comment]
抱歉，今天才有时间来研究这个问题。
已经修复，不论哪个macOS版本， 都会在/usr/local/opt/qt这个路径下拷贝副本，所以用这个路径就行了。
